# Auto-tag + Release (Recommended)
# Chains uplift and release to avoid GITHUB_TOKEN limitations
name: Release

on:
  push:
    branches: [main]

jobs:
  version:
    uses: jacaudi/github-actions/.github/workflows/uplift.yml@main
    with:
      use-github-app: true
    secrets:
      app-id: ${{ secrets.APP_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}

  release:
    needs: version
    if: needs.version.outputs.released == 'true'
    uses: jacaudi/github-actions/.github/workflows/release.yml@main
    with:
      release-tag: ${{ needs.version.outputs.version }}
      create-release: true
      build-type: none  # or: docker, goreleaser
