# Go SDK Release: Lint, Test, Auto-version, GoReleaser
# Requirements: go.mod, .goreleaser.yml
name: Go SDK Release

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    uses: jacaudi/github-actions/.github/workflows/lint.yml@main
    with:
      go: true

  test:
    uses: jacaudi/github-actions/.github/workflows/test.yml@main
    with:
      test-framework: go
      coverage: true

  release:
    needs: [lint, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: jacaudi/github-actions/.github/workflows/semantic-release.yml@main
    with:
      use-github-app: true
      hooks: goreleaser
      allow-initial-development-versions: true
    secrets:
      app-id: ${{ secrets.APP_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
