# Docker + Helm Release: Build, Scan, Publish Chart, Release
# Requirements: Dockerfile, charts/<name>/
name: Docker + Helm Release

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    uses: jacaudi/github-actions/.github/workflows/lint.yml@main
    with:
      yaml: true
      helm: true

  test:
    uses: jacaudi/github-actions/.github/workflows/test.yml@main

  release:
    needs: [lint, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: jacaudi/github-actions/.github/workflows/semantic-release.yml@main
    with:
      use-github-app: true
      allow-initial-development-versions: true
    secrets:
      app-id: ${{ secrets.APP_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}

  docker:
    needs: [release]
    if: needs.release.outputs.new-release-published == 'true'
    uses: jacaudi/github-actions/.github/workflows/docker-build.yml@main
    with:
      image-name: ${{ github.repository }}
      tags: |
        ghcr.io/${{ github.repository }}:${{ needs.release.outputs.new-release-version }}
        ghcr.io/${{ github.repository }}:latest

  scan:
    needs: [release, docker]
    if: needs.release.outputs.new-release-published == 'true'
    uses: jacaudi/github-actions/.github/workflows/image-scan.yml@main
    with:
      image-ref: ghcr.io/${{ github.repository }}:${{ needs.release.outputs.new-release-version }}
      image-digest: ${{ needs.docker.outputs.digest }}

  helm:
    needs: [release, scan]
    if: needs.release.outputs.new-release-published == 'true'
    uses: jacaudi/github-actions/.github/workflows/helm-publish.yml@main
    with:
      chart-name: myapp  # Change to your chart name
      chart-path: charts/myapp
      version: ${{ needs.release.outputs.new-release-version }}
