# Go SDK Release: Lint, Test, Auto-tag, GoReleaser
# Requirements: go.mod, .goreleaser.yml
name: Go SDK Release

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    uses: jacaudi/github-actions/.github/workflows/lint.yml@main
    with:
      go: true

  test:
    uses: jacaudi/github-actions/.github/workflows/test.yml@main
    with:
      framework: go
      coverage: true

  version:
    needs: [lint, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: jacaudi/github-actions/.github/workflows/uplift.yml@main
    with:
      use-github-app: true
    secrets:
      app-id: ${{ secrets.APP_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}

  release:
    needs: [lint, test, version]
    if: needs.version.outputs.released == 'true'
    uses: jacaudi/github-actions/.github/workflows/goreleaser.yml@main
    with:
      release-tag: ${{ needs.version.outputs.version }}
