name: Example Workflow Caller
# Example workflow demonstrating how to call the reusable workflows in this repository
# Use this as a reference for implementing in your own repositories

on:
  workflow_dispatch:
    inputs:
      run-lint:
        description: 'Run linting workflow'
        required: false
        type: boolean
        default: true
      run-tests:
        description: 'Run test workflow'
        required: false
        type: boolean
        default: true
      python-lint:
        description: 'Enable Python linting'
        required: false
        type: boolean
        default: false
      yaml-lint:
        description: 'Enable YAML linting'
        required: false
        type: boolean
        default: true
      shell-lint:
        description: 'Enable Shell linting'
        required: false
        type: boolean
        default: false

jobs:
  # Example: Lint workflow call
  lint:
    name: Lint
    if: ${{ github.event.inputs.run-lint == 'true' }}
    uses: jacaudi/github-actions/.github/workflows/lint.yml@main
    with:
      python: ${{ github.event.inputs.python-lint == 'true' }}
      yaml: ${{ github.event.inputs.yaml-lint == 'true' }}
      shell: ${{ github.event.inputs.shell-lint == 'true' }}
      fail-fast: false

  # Example: Test workflow call
  test:
    name: Test
    if: ${{ github.event.inputs.run-tests == 'true' }}
    uses: jacaudi/github-actions/.github/workflows/test.yml@main
    with:
      framework: auto
      coverage: false
      fail-on-error: false
      artifact-name: 'example-test-results'

  # Summary job that runs after lint and test
  summary:
    name: Summary
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: always()
    steps:
      - name: Generate Summary
        run: |
          echo "## Example Workflow Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "This workflow demonstrates calling the reusable workflows in this repository." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Workflow | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|--------|" >> $GITHUB_STEP_SUMMARY

          # Lint status
          LINT_STATUS="${{ needs.lint.result }}"
          if [[ "$LINT_STATUS" == "success" ]]; then
            echo "| Lint | :white_check_mark: Success |" >> $GITHUB_STEP_SUMMARY
          elif [[ "$LINT_STATUS" == "skipped" ]]; then
            echo "| Lint | :fast_forward: Skipped |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Lint | :x: $LINT_STATUS |" >> $GITHUB_STEP_SUMMARY
          fi

          # Test status
          TEST_STATUS="${{ needs.test.result }}"
          if [[ "$TEST_STATUS" == "success" ]]; then
            echo "| Test | :white_check_mark: Success |" >> $GITHUB_STEP_SUMMARY
          elif [[ "$TEST_STATUS" == "skipped" ]]; then
            echo "| Test | :fast_forward: Skipped |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Test | :x: $TEST_STATUS |" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Usage" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "To use these workflows in your repository, add:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`yaml" >> $GITHUB_STEP_SUMMARY
          echo "jobs:" >> $GITHUB_STEP_SUMMARY
          echo "  lint:" >> $GITHUB_STEP_SUMMARY
          echo "    uses: jacaudi/github-actions/.github/workflows/lint.yml@main" >> $GITHUB_STEP_SUMMARY
          echo "    with:" >> $GITHUB_STEP_SUMMARY
          echo "      python: true" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "  test:" >> $GITHUB_STEP_SUMMARY
          echo "    uses: jacaudi/github-actions/.github/workflows/test.yml@main" >> $GITHUB_STEP_SUMMARY
          echo "    with:" >> $GITHUB_STEP_SUMMARY
          echo "      framework: pytest" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
