# Docker + Helm Release: Build, Scan, Publish Chart, Release
# Requirements: Dockerfile, charts/<name>/
name: Docker + Helm Release

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    uses: jacaudi/github-actions/.github/workflows/lint.yml@main
    with:
      yaml: true
      helm: true

  test:
    uses: jacaudi/github-actions/.github/workflows/test.yml@main

  version:
    needs: [lint, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: jacaudi/github-actions/.github/workflows/uplift.yml@main
    with:
      use-github-app: true
    secrets:
      app-id: ${{ secrets.APP_ID }}
      app-private-key: ${{ secrets.APP_PRIVATE_KEY }}

  docker:
    needs: [version]
    if: needs.version.outputs.released == 'true'
    uses: jacaudi/github-actions/.github/workflows/docker-build.yml@main
    with:
      image-name: ${{ github.repository }}

  scan:
    needs: [version, docker]
    if: needs.version.outputs.released == 'true'
    uses: jacaudi/github-actions/.github/workflows/image-scan.yml@main
    with:
      image-ref: ghcr.io/${{ github.repository }}:${{ needs.version.outputs.version }}
      image-digest: ${{ needs.docker.outputs.digest }}

  helm:
    needs: [version, scan]
    if: needs.version.outputs.released == 'true'
    uses: jacaudi/github-actions/.github/workflows/helm-publish.yml@main
    with:
      chart-name: myapp  # Change to your chart name
      chart-path: charts/myapp

  release:
    needs: [version, docker, helm]
    if: needs.version.outputs.released == 'true'
    uses: jacaudi/github-actions/.github/workflows/release.yml@main
    with:
      release-tag: ${{ needs.version.outputs.version }}
      create-release: true
      build-type: none
    secrets: inherit
